# ------------------------------------------------
# CI CD pipeline for kubernetes deployments of a python application
# ------------------------------------------------
# Written by Christopher Becker
# christopher.becker@genesis-mining.com
# ------------------------------------------------

include:
  - project: genesis-group/office-it-bcc/infra-ci-templates
    file: build-repositories.yaml

services:
  - name: docker:stable-dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

# ------------------------------------------------
# Global variables
# ------------------------------------------------
variables:

# For Docker Build
  PY_BASE_IMAGE: python:3.7
  APP_PATH: src

# For Helm Build
  HELM_PATH: helm/cluster-config-operator
  HELM_VALUES_PATH: helm/cluster-config-operator/values.yaml



stages:
  - prepare
  - build
  - release
  - trigger

########################################################################
# PREPARE STAGE                                                        #
########################################################################

helm lint:
  extends: .helm lint

helm dry run:
  extends: .helm dry run

check code quality:
  extends: .check code quality

python lint:
  extends: .python lint

helm connect stable repo:
  extends: .helm connect stable repo


########################################################################
# BUILD STAGE                                                          #
########################################################################

docker image build:
  extends: .docker image build

helm repo build:
  extends: .helm repo build

########################################################################
# RELEASE STAGE                                                        #
########################################################################

update versioncontrol:
  extends: .update versioncontrol

########################################################################
# DEPLOY STAGE                                                         #
########################################################################

trigger deployment:
  extends: .gitlab trigger