apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clustersecrets.genesis-mining.com
spec:
  scope: Cluster
  group: genesis-mining.com
  version: v1beta1
  names:
    kind: ClusterSecret
    plural: clustersecrets
    singular: clustersecret
    shortNames:
      - cs
  additionalPrinterColumns:
    - JSONPath: .spec.name
      description: Name of the upstream secret
      name: Name
      type: string
    - JSONPath: .spec.namespace
      description: Namespace of the upstream secret
      name: Namespace
      type: string
    - JSONPath: .metadata.creationTimestamp
      name: Age
      type: date
  validation:
    openAPIV3Schema:
      description: Points to a secret which will be deployed clusterwide
      properties:
        spec:
          required:
            - name
            - namespace
          properties:
            name:
              type: "string"
              minimum: 1
            namespace:
              type: "string"
              minimum: 1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterconfigmaps.genesis-mining.com
spec:
  scope: Cluster
  group: genesis-mining.com
  version: v1beta1
  names:
    kind: ClusterConfigMap
    plural: clusterconfigmaps
    singular: clusterconfigmap
    shortNames:
      - ccm
  additionalPrinterColumns:
    - JSONPath: .spec.name
      description: Name of the upstream configmap
      name: Name
      type: string
    - JSONPath: .spec.namespace
      description: Namespace of the upstream configmap
      name: Namespace
      type: string
    - JSONPath: .metadata.creationTimestamp
      name: Age
      type: date
  validation:
    openAPIV3Schema:
      description: Points to a configmap which will be deployed clusterwide
      properties:
        spec:
          required:
            - name
            - namespace
          properties:
            name:
              type: "string"
              minimum: 1
            namespace:
              type: "string"
              minimum: 1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterconfig
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - genesis-mining.com
    resources:
      - clustersecrets
      - clusterconfigmaps
    verbs: 
      - get
      - list
      - watch
---
apiVersion: v1
kind: Pod
metadata:
  name: operator
spec:
  serviceAccountName: operator
  containers:
  - name: operator
    imagePullPolicy: Always
    image: eu.gcr.io/internal-services-272317/clusterconfig:2.0.0-test1
    env:
      - name: APPLY_EXISTING
        value: "false"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator
subjects:
- kind: ServiceAccount
  name: operator
  namespace: config-operator
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io