{{- if .Values.crd.clustersecret.enabled -}}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clustersecrets.genesis-mining.com
  labels:
    app: {{ template "cluster-config.name" . }}
{{- include "cluster-config.labels" . | indent 4 }}
{{- if .Values.crd.clustersecret.crdLabels }}
{{- toYaml .Values.crd.clustersecret.crdLabels | indent 4}}
{{- end}}
spec:
  scope: Cluster
  group: genesis-mining.com
  version: v1beta1
  names:
    kind: ClusterSecret
    plural: clustersecrets
    singular: clustersecret
    shortNames:
      - csc
  additionalPrinterColumns:
    - JSONPath: .spec.name
      description: Name of the upstream secret
      name: Name
      type: string
    - JSONPath: .spec.namespace
      description: Namespace of the upstream secret
      name: Namespace
      type: string
    - JSONPath: .metadata.creationTimestamp
      name: Age
      type: date
  validation:
    openAPIV3Schema:
      description: Points to a secret which will be deployed clusterwide
      metadata:
        type: object      
      properties:
        spec:
          required:
            - name
            - namespace
          properties:
            name:
              type: "string"
              description: Name of the secret used for cloning
            namespace:
              type: "string"
              description: Namespace of the secret used for cloning
            includeNamespaces:
              type: array
              description: Only namespaces with matching pattern are used
            excludeNamespaces:
              type: array
              description: No namespaces with matching pattern are used
{{- end -}}
