apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ template "cluster-config.fullname" . }}
  labels:
    app: {{ template "cluster-config.name" . }}
{{- include "cluster-config.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "cluster-config.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "cluster-config.name" . }}
{{- include "cluster-config.labels" . | indent 8 }}
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
      annotations:
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
    {{- if .Values.rbac.enabled }}
      serviceAccountName: {{ template "cluster-config.fullname" . }}
    {{- else }}
      serviceAccountName: {{.Values.rbac.serviceAccount}}
    {{- end }}
    {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
    {{- end }}
    {{- if .Values.imagePullSecrets.enabled }}
      imagePullSecrets:
      - name: {{ template "cluster-config.fullname" . }}-imagepullsecret
    {{- end }}
      containers:
        - name: {{ template "cluster-config.name" . }}
          image: "{{.Values.image.repository}}:{{.Values.image.version}}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.livenessProbe.periodSeconds}}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
    {{- end}}
    {{- if .Values.readinessProbe.periodSeconds}}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
    {{- end}}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
