{{- if .Values.imagePullSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cluster-config.fullname" . }}-imagepullsecret
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "cluster-config.name" . }}-imagepullsecret
{{- include "cluster-config.labels" . | indent 4 }}
  type: kubernetes.io/dockerconfigjson
data: {{ b64enc .Values.imagePullSecrets.config_json }}
{{- end }}