{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cluster-config.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "cluster-config.name" . }}
{{- include "cluster-config.labels" . | indent 4 }}
{{- end }}